version: 2.1
orbs:
  node: circleci/node@1.1.6
  docker: circleci/docker@1.3.0
jobs:
  npm_install_and_test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test

workflows:
  dev:
    jobs:
      - npm_install_and_test:
          filters:
            branches:
              only: dev
  master:
    jobs:
      - docker/publish:
          requires:
            - npm_install_and_test
          image: domojesse/resume-as-a-service
          tag: 'latest,prod'
